--------------------------------------------------------
-- Archivo creado  - martes-julio-23-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Materialized View VM_TIEMPO_EMPRESA_INGRESOS
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "P54G4_OLTP_HR"."VM_TIEMPO_EMPRESA_INGRESOS" ("CÓDIGO_AÑO", "ALQUILER_EQUIPOS_COMPUTACION", "DESCRIPCION_TAMAÑO_EMPRESA", "GRUPO_SERVICIO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSP_GBD_4263" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT A.CODANIO as código_año,  A.ALQ_EQUIPCOMP as alquiler_equipos_computacion
 , B.DES_TAM as descripcion_tamaño_empresa , C.GRUP as grupo_servicio
 FROM TABLA_GENERAL A ,D_TAMAÑO B, D_GRUP_SERV C
 WHERE A.TAMANIO = B.ID_D_TAMAÑO AND A.TAMANIO = 5 AND A.ALQ_EQUIPCOMP != 0;
 

   COMMENT ON MATERIALIZED VIEW "P54G4_OLTP_HR"."VM_TIEMPO_EMPRESA_INGRESOS"  IS 'snapshot table for snapshot P54G4_OLTP_HR.VM_TIEMPO_EMPRESA_INGRESOS';
