--------------------------------------------------------
-- Archivo creado  - martes-julio-23-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Materialized View VM_UBICACION_TIEMPO_IMPUESTOS
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "P54G4_OLTP_HR"."VM_UBICACION_TIEMPO_IMPUESTOS" ("PROVINCIA", "REGION", "AÑO", "DESCRIPCION_TAMAÑO_EMPRESA", "GRUPO_SERVICIO", "IMPUESTO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSP_GBD_4263" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT U.PROV_DES as PROVINCIA, R.DES_PROV as REGION,  A.CODANIO as AÑO
 , B.DES_TAM as descripcion_tamaño_empresa , C.GRUP as grupo_servicio, A.IMPUESTO as Impuesto
 FROM TABLA_GENERAL A ,D_TAMAÑO B, D_GRUP_SERV C, D_PROVINCIA U, D_REGUION R
 WHERE A.TAMANIO = B.ID_D_TAMAÑO AND A.TAMANIO =B.id_d_tamaño AND A.ALQ_EQUIPCOMP = A.ALQ_EQUIPCOMP AND A.WREGION= R.ID_REG;
 

   COMMENT ON MATERIALIZED VIEW "P54G4_OLTP_HR"."VM_UBICACION_TIEMPO_IMPUESTOS"  IS 'snapshot table for snapshot P54G4_OLTP_HR.VM_UBICACION_TIEMPO_IMPUESTOS';
